* Project

In tools 1 we are concerned with data cleaning and exploratory analysis.
Please select a project having enough scope for following activities.

Project requires submission of  .ipynb notebook  file  and a compiled pdf file.

Final report, should read like a data driven story/scientific study (data science). This is really important if you want to publish you story as 
blog in the web or share with stakeholders.


** Dataset and motivation slide (2 points)
  How/why  dataset was collected and describe the meta data of your dataset.

** Actual task definition/Research Question (2 points) 
  What real world problem you trying to solve. *What is input and output of your analysis.*

** Quality of cleaning (6 points, 2 points each)
 - Data Cleaning and type conversion activity. Anything unusual you have to face in this activity. Please share.
 - What you did about missing values and why?
 - Data summary statistics and interpretation.

** Visualization (8 points, 2 points each)
  - Data Visualization activity(box plot, bar plot, violin plot, pairplot to see relationship and distribution etc).
  - Describe any thing you find in the data after each visualization.
  - What data  visualization help you understanding data distribution.
  - What did you do about possible outlier as per data distribution visualization. (Did you confirm it with your client if it is actually an outlier or put a disclosure statement in notebook if you decided to remove it.)


