* Project presentation

A 12 -15 slide presentation must contain following sections.*
*Please present this presentation in pre presentation(20 minutes, 15 th May, Not graded) and final project presentation(25 minutes, 31 May)*

** Dataset and motivation slide (2 points)
  How/why  dataset was collected and describe the meta data of your dataset. 

** Research Questions (2 points)
  What real world problem you trying to solve. *What is input and output of your analysis.*

**  Data munging/Data wrangling and statistical summary (4 points, 2 points each)
 - Anything unusual you have to face in this data cleaning activity. Please share.
 - Data summary statistics and interpretation.

**  Main visualization (4 points, 2 points each)
  - Data Visualization activity(box plot, bar plot, violin plot, pairplot to see relationship and distribution etc).
  - Describe any thing you find in the data after each visualization.

** Modelling activity/evaluation/conclusion(5 points, depending on whether you are building a model or analytical website) 
  - if you are bulid a model like logistic/linear regression (3 points, 1 point each)
    + What kind of hypothesis you tested about predictors(independent variables).
    + What motivated you to use this model.
    + Model parameter/coefficient interpretation.
  - If you are building analytical website. (3 points, 1 point each)
    + Describe tools for building website and database(tables etc.)
    + Snapshot of main Dash board webpage.
    + Snapshot of one other data driven analytic webpage and its description.
  -  What is current evaluation or finding of the project. is there some metric you can report?(2 points)





