* Data Science Tools 1
  - Course: Data Science Project 1 COMP-4447-1
  - Class time: M, Wed  07:00 PM -  08:50 PM  |Engineering & Computer Science | Room 410
  - Instructor: /Pooran Singh Negi, pooran.negi@du.edu/ [[https://sites.google.com/site/poorannegi/][webpage]]
  - Office: 470
  - Office Hours: Tue, Thu,  2.00 p.m. - 4.00 p.m. Email for 1-on-1 help.
   
** Books 
   - [[https://www.amazon.com/Python-Data-Analysis-Wrangling-IPython/dp/1491957662/ref=sr_1_2?s=books&ie=UTF8&qid=1522206082&sr=1-2&keywords=pandas][Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython 2nd Edition]]  by Wes McKinney. It is available online from [[https://library.du.edu/][library]]

*** Other books     

   - [[http://greenteapress.com/thinkstats2/html/index.html][Think Stats: Exploratory Data Analysis in Python]]
   -[[http://greenteapress.com/wp/think-bayes/][ Think Bayes]]  
   - [[http://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/][Probabilistic Programming & Bayesian Methods for Hackers]]
** Optional material
More to come
* Course Description
It is recommended that you consult this github page often for material related to this course. You should check your e-mail periodically for messages.
Assignments will be upload here and in the [[https://canvas.du.edu/login/ldap][canvas]].

The main objective of data science tools 1 is to learn various tools to perform data analysis. Focus in tool1 is data cleanup, summarization ,and visualization.
It is more like a hacking skill set but our primary focus will be on the scientific python  and Linux ecosystem. We'll use [[http://jupyter.org/][jupyter notebook/lab]] for in the class and homeworks. This should make our learning interactive.

For the final project, students will work through  individual or team projects applying course-work
to the full data lifecycle within a particular domain. The focus will also be
on best data science/software engineering practices and reproducible work.

*Please select one of the projects by January 20th  as per your preference.* There will be a homework asking about the detail of your final project. We'll provide feedback about feasibility as the final project.


** Syllabus
*This syllabus is subject to change at the discretion of the instructor*.
- Jupyter Notebook for reproducible workflow.
- Data science and EDA.
- Git tools work flow.
- Data science at command prompt. Linux command line, bash,  basic awk and sed.
- Data collection and ingestion(web scrapping and reading datasets + pandas).
- Data cleanup and imputation + Pandas.
- Data summarization and visualization+ panda(groupby, apply, aggregate etc).
- Final projects, Can be based on initial capstone work?
- Go over some some topics as per students demands.
- more to come

 *Linux command line and scientific python ( primarily numpy, matplotlib, request, seaborn, basic pandas) will be used throughout the course.*

* Grading
*There will be a final project and coding/analysis homework assignments. We'll drop one of your worst assignment grade*.

One has to do  a *final project*  to full fill course requirements.
There will be a final presentation of the work done during current quarter.
You will be required to  submit a final report in the jupyter notebook format.

** [[./project_presentation.org][project presentation grading  rubric]]
** [[./project_rubric.org][final project report grading rubric]]

** Dates

|--------------------------------------------------------------------------------------------------------+-----|
| coding Homework                                                                                        | 50% |
|--------------------------------------------------------------------------------------------------------+-----|
| pre presentation, xx March                                                                             |     |
|--------------------------------------------------------------------------------------------------------+-----|
| midterm ??, xx Feb in class                                                                               | 25% |
|--------------------------------------------------------------------------------------------------------+-----|
| final project presentation, 15 minutes, xx March in class                                              | 15% |
|--------------------------------------------------------------------------------------------------------+-----|
| final project report, due xx March, please refer to above final report format for submission guideline | 20% |
|--------------------------------------------------------------------------------------------------------+-----|
|                                                                                                        |     |

** Final course grading rubric

grade range [('A', >=93), ('A_minus', >=89), ('B_plus', >=85), ('B', >=81), ('B_minus', >=77), ('C_plus', >=73), ('C', >=69), ('C_minus', >=65),
 ('D_plus', >61), ('D', >=57), ('D_minus', >=53),  ('F', < 53)])


* Honor code
All members of the University of Denver community are expected to uphold the values of Integrity, Respect, and Responsibility.
These values embody the standards of conduct for students, faculty, staff, and administrators as members of the University community. 
Our institutional values are defined as:

Integrity: acting in an honest and ethical manner;

Respect: honoring differences in people, ideas, experiences, and opinions;

Responsibility: accepting ownership for one's own behavior and conduct.

Please respect DU [[https://www.du.edu/studentlife/studentconduct/honorcode.html][Honor Yourself, Honor the Code]]

* Students with Disabilities
Students with recognized disabilities will be provided reasonable
accommodations, appropriate to the course, upon documentation of the disability with a Student
Accommodation Form from the Disability Services Program. *To receive these accommodations, you must request the specific accommodations, by submitting them to the instructor in writing,
by the end of first week of classes.* Visit [[https://www.du.edu/studentlife/disability/][CAMPUS LIFE & INCLUSIVE EXCELLENCE]] webpage for details.

* Withdrawal Policy
Please see [[https://www.du.edu/registrar/calendar/][registrar calender]] for Academic deadlines. *We'll strictly follow the deadlines.*

* Projects
  You can choose your own dataset.
   - more to come ...
     
* Software Installation
** Python
We want to have same experience at any part of data science life cycle. Please follow steps as
per your operating system.

Please install [[https://www.anaconda.com/download/][Anaconda for Python 3.7 data science platform]]. Please install Download Anaconda Distribution
*Version 2018.12 | Release Date: December 21, 2018*. Please install it before coming in the class. 
We'll be doing live exercises almost in all the classes.
See the youtube link [[https://www.youtube.com/watch?v=OOFONKvaz0A][Installing Anaconda, Jupyter Notebook]]. 

*** Linux and Mac Os installation.
Please choose right operating system from anaconda site.

*** Window based installation
Please install Linux Subsystem on window 10. Follow the instruction in this post [[https://medium.com/hugo-ferreiras-blog/using-windows-subsystem-for-linux-for-data-science-9a8e68d7610c][Using Windows Subsystem for Linux for Data Science]]
by Hugo Ferreira for installing Linux and Anaconda on windows.

Note that we'll be using Version 2018.12 | Release Date: December 21, 2018. When you follow above post please download
Anaconda3-2018.12-Linux-x86_64.sh  using following command. Author uses old version.

*wget https://repo.continuum.io/archive/Anaconda3-2018.12-Linux-x86_64.sh* 

while following *Install Anaconda* section in blog post.


You can also watch this [[https://www.youtube.com/watch?v=Cvrqmq9A3tA][video]] to see installation of Windows 10 Bash & Linux Subsystem Setup but you still have to
install Anaconda as mentioned in above blog post.


You can also go to my  [[https://github.com/psnegi/PythonForReproducibleResearch][python for reproducible research]]  github repository and start by running pythonBasic.ipynb notebook.
I will go over basic of python and jupyter notebook.

*** Python learning resources
   - [[https://try.jupyter.org/][try python notebook online without installing anything]]
   - [[http://pythontutor.com/live.html#mode%3Dedit][Runs and visualizes your python code]]
   - [[https://docs.python.org/3/tutorial/index.html][The Python Tutorial]]  
*** data analysis tools in python
    - [[https://pandas.pydata.org/][pandas]]

* Homeworks
*No late hw will be accepted*

|-------+-----------------------------------------------------------------+---------------------|
| HW no | desciption and link                                             |                     |
|       |                                                                 | Due date            |
|-------+-----------------------------------------------------------------+---------------------|

* Course Activity
|       Date | Reading/Coding Assignments                        | class activity                                                                                                                                                     |
|------------+---------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------|



